<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Home' => 'Trang chủ',
    'Add to cart' => 'Thêm giỏ hàng',
    'Description' => 'Chi tiết',
    'Information' => 'Thông tin',
    'Reviews' => 'Bình luận',
    'Most popular products' => 'Sản phẩm nổi bật nhất',
    'View' => 'Xem',
    'More details' => 'Chi tiết',
    'New Arrivals' => 'Nhiều lượt xem',
    'My Account' => 'Tài khoản',
    'Checkout' => 'Thanh toán',
    'Log In' => 'Đăng nhập',
    'New items' => 'Sản phẩm mới',
    'What do you want to search?' => 'Bạn muốn tìm kiếm sản phẩm gì?',
    'Product' => 'Sản phẩm',
    'items' => 'sản phẩm',
    'Shopping cart' => 'Giỏ hàng',
    'Image' => 'Ảnh',
    'Quantity' => 'Số lượng',
    'Unit price' => 'Giá',
    'Total' => 'Tổng',
    'Sub total' => 'Tổng phụ',
    'Shipping cost' => 'Vận chuyển',
    'Continue shopping' => 'Tiếp tục mua sắm',
    'Step' => 'Bước',
    'Customer information' => 'Thông tin khách hàng',
    'Confirm Order' => 'Xác nhận đơn hàng',
    'Cancel' => 'Hủy',
    'Payment Method' => 'Phương thức thanh toán',
    'Please select the preferred payment method to use on this order.' => 'Vui lòng chọn phương thức thanh toán ưa thích để sử dụng cho đơn đặt hàng này.',
    'Transaction Payment (COD)' => 'Thanh toán khi giao dịch (COD)',
    'Bank transfer' => 'Chuyển khoản qua ngân hàng',
    'Continue' => 'Tiếp tục',
    'Price' => 'Giá',
    'Name' => 'Họ tên',
    'Address' => 'Địa chỉ',
    'Phone' => 'Số điện thoại',
    'Delivery time' => 'Thời gian giao hàng',
    'Message' => 'Lời nhắn',
    'Payments do not need an account.' => 'Thanh toán không cần tài khoản',
    'By creating an account you will be able to shop faster, be up to date on an order\'s status, and keep track of the orders you have made.' => 'Bằng cách tạo tài khoản, bạn sẽ có thể mua hàng nhanh hơn, cập nhật về tình trạng của đơn đặt hàng và theo dõi các đơn đặt hàng bạn đã thực hiện.',
    'Login' => 'Đăng nhập',
    'Register' => 'Đăng kí',
    'Username' => 'Tên đăng nhập',
    'Password' => 'Mật khẩu',
    'Remember Me' => 'Nhớ tôi',
    'If you forgot your password you can' => 'Nếu bạn quên mật khẩu của mình, bạn có thể',
    'reset it' => 'đặt lại nó',
    'Full name' => 'Họ và tên',
    'Repeat Password' => 'Nhập lại mật khẩu',
    'Important' => 'Quan trọng',
    'Login to track your order, save your favorite product list, receive attractive offers.' => 'Đăng nhập để theo dõi đơn hàng, lưu danh sách sản phẩm yêu thích, nhận nhiều ưu đãi hấp dẫn.',
    'Request password reset' => 'Lấy lại mật khẩu',
    'First name' => 'Họ và đêm',
    'Last name' => 'Tên',
    'Update' => 'Cập nhật',
    'Account Information' => 'Thông tin tài khoản',
    'Shipping address' => 'Địa chỉ giao hàng',
    'Order' => 'Đơn hàng',
    'Logout' => 'Đăng xuất',
    'Your account information has been updated successfully.' => 'Thông tin tài khoản của bạn đã cập nhật thành công.',
    'Province' => 'Tỉnh',
    'District' => 'Huyện'
];